# Generated by Django 2.1.5 on 2019-02-19 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of The item')),
                ('code', models.CharField(max_length=20, verbose_name='Code of the item')),
                ('type', models.CharField(choices=[('1', '1:1'), ('2', '2:1'), ('3', '3:1')], max_length=8, verbose_name='Type of raw material')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of The item')),
                ('cost', models.FloatField(verbose_name='Cost of The item')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of purchase')),
                ('quantity', models.IntegerField(default=django.utils.timezone.now, verbose_name='Quantity of purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Rawmaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of The Raw Material/ Ingredient')),
                ('measurmentunit', models.CharField(choices=[('KG', 'Kilogram'), ('LT', 'LITRE'), ('UT', 'Unit')], max_length=8, verbose_name='Unit of measurement')),
                ('type', models.CharField(choices=[('VGT', 'Vegitables'), ('MT', 'Meat'), ('GRC', 'Groceries')], max_length=8, verbose_name='Type of raw material')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='rawmaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rmsapp.Rawmaterial', verbose_name='Name of Item to purchase'),
        ),
    ]
